### ISSUE TITLE
Переписать «Требования по окружению»

### ISSUE THREAD

**Issue by taqyon** [atls/convention#19]
#### Материалы 
- https://gist.github.com/TFK70/ba62e4fda2d7bdea67d8deb664864d92
- https://github.com/atls/convention/wiki/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF%D1%8B
- https://gist.github.com/TFK70/51c0f46a916a3ce71976774b51c66e1d

**Comment by taqyon** [comment]
# Environment requirements

Привет Username! Чтобы приступить к началу работы, нужно подготовить рабочее окружение. 
*Надо добавить наверное еще что-то.* 

##  Ubuntu@20.04

Абзац про линукс.

- [ ] Я сделал

## IDE

Для работы с кодом обязательно потребуется [IDE](https://ru.wikipedia.org/wiki/%D0%98%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%B0%D1%8F_%D1%81%D1%80%D0%B5%D0%B4%D0%B0_%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8). 

Мы обычно работаем в **IDE_NAME**, часто в качестве IDE выбирают – *IDE_NAMES*. Но ты можешь выбрать что душе угодно.

- [ ] Я сделал

## node@16+

Чё такое и как устанавливать в кратце. 

- [ ] Я сделал

### yarn (установленный через npm)

Чё такое и как устанавливать в кратце. 

- [ ] Я сделал

## Email

Почтовый клиент и привязанная к нему почта, которая привязана к гитхабу для получения всех уведомлений

- [ ] Я сделал
## Некоторая настройка Github

-   [ ] GPG
-   [ ] Автоподпись коммитов (настраивается в git)
-   [ ] SSH
-   [ ] 2FA (использовать Яндекс.Ключ)

**Comment by taqyon** [comment]
@TorinAsakura @TFK70 добавил файл, там есть пробелы, было бы круто если бы вы что-то заполнили. Нужен контент кароч.

файл: https://github.com/atls/convention/blob/master/docs/Environment%20Requirements.md

**Comment by taqyon** [comment]
@TorinAsakura @TFK70 

Внёс изменения: https://github.com/atls/convention/commit/b49167a1b4d7b133d26aa7e886b14ab07d6b3752

Там надо линк добавить на офишал гайд по установке Ubuntu, я чёто не смог найти. 


## Также есть предложение

Когда мы вчера созванивались, то условились что прежде чем кандидат получит свой личный репозиторий в github, он должен настроить себе рабочее окружение. 

Так вот, я предлагаю такую схему: С**разу всё пушить в Github.** Отдавать все начальные (ключевые) таски туда. В том числе настройку окружения. Если настроить шаблон repo должным образом, то это избавит от дополнительной нагрузки ментора. А вся исчерпывающая инфа будет уже в репозитории. Тут главный аспект — это правильный шаблон repo. 

Что думаете?

**Comment by TFK70** [comment]
@taqyon то есть ты предлагаешь создавать репозиторий в академии для 100% кандидатов?

**Comment by taqyon** [comment]
> @taqyon то есть ты предлагаешь создавать репозиторий в академии для 100% кандидатов?

В целом да. В этом сценарии предполагается, что первые два разговора человек прошёл и справится с поставленными задачами.

**Comment by taqyon** [comment]
@TFK70 @TorinAsakura пофиксил файл с учётом последнего разговора. Ориентировался на то, что он будет даваться в github pages или откуда-то еще. 

Проверьте, пожалуйста. Если всё в порядке и текущая редакция устраивает, то я закрываю тикет.

**Comment by TorinAsakura** [comment]
> @TFK70 @TorinAsakura пофиксил файл с учётом последнего разговора. Ориентировался на то, что он будет даваться в github pages или откуда-то еще.
> 
> Проверьте, пожалуйста. Если всё в порядке и текущая редакция устраивает, то я закрываю тикет.
> 
> файл: https://github.com/atls/convention/blob/master/docs/Environment%20Requirements.md

Не нужно давать [альтернативных](https://github.com/atls/convention/blob/master/docs/Environment%20Requirements.md#как-ставить) способов что-то установить, когда ты даёшь альтернативу, ты не можешь чётко подсчитать всевозможные сценарии, а когда идёт работа по (пере)обучению людей это очень важный фактор, так как он экономит время 

Ноду нужно ставить через aptitude (apt install nodejs@16) и никак иначе

yarn, также, нужно ставить через системный пакетный менеджер, чтобы не думать о возможных артефактах
```bash
apt install --no-install-recommends yarn
```

@TFK70 я вам всем давал ссылку как активировать автоподпись для коммитов, найди её и прикрепи к таске

**Comment by taqyon** [comment]
@TorinAsakura @TFK70 Привет! Я перечитал файл с изменениями, и он выглядит как законченный на данный момент. Могу закрывать тикет?

**Comment by TorinAsakura** [comment]
@taqyon +
