### ISSUE TITLE
Насчет шаблонов

### ISSUE THREAD

**Issue by taqyon** [atls/convention#26]
### Насчет шаблонов

Сюда точно нужно добавить md шаблон который люди должны использовать при обращении за помощью. Если этого не делать - первым вопросом человека будет что-то типа: `Ну вот у меня кароч в какой-то консоли вот это вывело <какой-то непонятный лог> хз че это я потыкал чет не понял помогите` **даже** если сообщение было опубликовано на гитхабе, в телеге о помощи просят еще хуже

В конечном итоге обращения должны выглядеть примерно [так](https://github.com/atls-academy/brusselboy.github.io/issues/12#issuecomment-1158823075). По идее за пример можно взять любое сообщение из треда или одной из других последних задач в репе Кирилла

Я уже пытался подготовить на этой почве шаблон обращения за помощью, получилось что-то [такое](https://gist.github.com/TFK70/07f469bb31e64481b22d0f66d43c8b88) (во многом дублирует [этот](https://github.com/atls-academy/brusselboy.github.io/blob/master/.github/ISSUE_TEMPLATE/bug.md) шаблон)

В целом можно использовать и его, если он на твой и @TorinAsakura взгляд валиден, **но** главное упомянуть, что ни один из пунктов не должен быть проигнорирован, человек должен хотя бы прокомментировать отсутствие того или иного пункта

_Originally posted by @TFK70 in https://github.com/atls/convention/issues/25#issuecomment-1160639264_

**Comment by TFK70** [comment]
@taqyon 

### Примеры того как не надо сообщать об ошибках

1. https://github.com/atls-academy/dok959.github.io/issues/1#issuecomment-1157559372

- Нет коммита и пра
- Лог скинут скриншотом
- Просто допом: если бы он сделал коммит, мог бы не дублировать свое окружение

**P.S.** я еще попросил этот коммент отредактировать, первая ревизия была чем-то типа:

`
Появляется ошибка на проекте <СКРИНШОТ с ошибкой>, не знаю куда копать
`

Все)

2. https://github.com/ilink-pro/web/issues/33#issue-1252434199

- Проигнорированы некоторые пункты шаблона
- Не стёрты шаблонные строки
- Да и в целом шаблон не особо подходит под вопрос, 80% воды и 20% контента
