### ISSUE TITLE
Дополнить раздел отладки кода

### ISSUE THREAD

**Issue by TorinAsakura** [atls/convention#47]
### Какого рода задача?

Дополнить документацию

### Что и где будем менять?

https://github.com/atls/convention/wiki/Отладка-кода

**Comment by Nelfimov** [comment]
## Конкретизируем задачу:

Необходимо внести краткий гайд как пользоваться средствами дебага в IDE JetBrains для веб разработки.

**Comment by Nelfimov** [comment]
Добавил, посмотри пожалуйста:
https://github.com/atls/convention/wiki/Отладка-кода#дебаг-в-ide-от-jetbrains-webstorm-intellij

**Comment by TorinAsakura** [comment]
Приемлемо.
